config/routes.rb
LonLat::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  resources :points

   root :to => 'points#index'

end

app/models/point.rb
class Point < ActiveRecord::Base
  attr_accessible :lat, :lng
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  # GET /points
  # GET /points.json
  def index
    @points = Point.find(:all, :order => "id desc", :limit => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @points }
    end
  end

  # GET /last
  # GET /last.json
  def last
    @point = Point.last

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @points }
    end
  end


  # GET /points/1
  # GET /points/1.json
  def show
    @point = Point.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @point }
    end
  end

  # GET /points/new
  # GET /points/new.json
  def new
    @point = Point.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @point }
    end
  end

  # GET /points/1/edit
  def edit
    @point = Point.find(params[:id])
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(params[:point])

    respond_to do |format|
      if @point.save
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render json: @point, status: :created, location: @point }
      else
        format.html { render action: "new" }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /points/1
  # PUT /points/1.json
  def update
    @point = Point.find(params[:id])

    respond_to do |format|
      if @point.update_attributes(params[:point])
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point = Point.find(params[:id])
    @point.destroy

    respond_to do |format|
      format.html { redirect_to points_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  

  def home
    @points = Point.last

    respond_to do |format|
      formal.html #home.html.erb
    end
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LonLat</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <!--  <%= javascript_include_tag "application" %> -->
  <%= csrf_meta_tags %>

<%= yield %>

</html>

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br />
    <%= f.text_field :lng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">

  function initialize() {
    <% @points.find(1) do |point| %>
    var myLatLng = new google.maps.LatLng(<%= point.lng %>, <%= point.lat %>);
    <% end %>


    var myOptions = {
      zoom: 16,
      center: myLatLng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

    var marker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      animation: google.maps.Animation.DROP
    });


    var contentString = '<div id="content">'+
        '<div id="siteNotice">'+
        '</div>'+
        '<strong>Last Location</strong><br>'+
        '<p id="firstHeading" class="firstHeading"><% @points.find(1) do |point| %> <%= point.lng %>, <%= point.lat %>,' + 
        '<br> <%=point.updated_at %> <% end %> </p>'+

        '</div>';

    var infowindow = new google.maps.InfoWindow({
        content: contentString
    });

    google.maps.event.addListener(marker, 'click', function() {
   infowindow.open(map,marker);
});
infowindow.open(map,marker);



    var travelCoordinates = [

    <% @points.each do |point| %>
        new google.maps.LatLng(<%= point.lng %>, <%= point.lat %>),
    <% end %>
    
    ];

    var travelPath = new google.maps.Polyline({
      path: travelCoordinates,
      strokeColor: "#FF0000",
      strokeOpacity: 1.0,
      strokeWeight: 2
    });

    travelPath.setMap(map);

  }
</script>
</head>
<body onload="initialize()">
  <div id="map_canvas"></div>

</body>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<%= @point.lat %>
<%= @point.lng %>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Point %><br />
    <%= f.text_field :Point %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br />
    <%= f.text_field :lng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">

  function initialize() {
    var myLatLng = new google.maps.LatLng(14.571119, 121.047642);
    var myOptions = {
      zoom: 16,
      center: myLatLng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

    var marker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      title: "Current Location"
    });


    var travelCoordinates = [
        new google.maps.LatLng(14.571119, 121.047642),
        new google.maps.LatLng(14.571601, 121.051891),
        new google.maps.LatLng(14.576253, 121.059262),
    ];

    var travelPath = new google.maps.Polyline({
      path: travelCoordinates,
      strokeColor: "#FF0000",
      strokeOpacity: 1.0,
      strokeWeight: 2
    });

    travelPath.setMap(map);

  }
</script>
</head>
<body onload="initialize()">
  <div id="map_canvas"></div>
</body>